# Generated by Django 2.2.6 on 2020-02-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='by',
        ),
        migrations.AddField(
            model_name='blog',
            name='by',
            field=models.ManyToManyField(to='api.Users'),
        ),
    ]
