# Generated by Django 2.2.6 on 2020-02-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200223_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='by',
            new_name='users',
        ),
    ]
